// Generated by CoffeeScript 1.9.3

/* Functions that actually init the game */


/* Begins init processing */

(function() {
  this.init = function() {
    return this.initStart();
  };


  /* Set up a PIXI stage - part before asset loading */

  this.initStart = function() {
    var dumTex, g, margin, menuHeight, offset;
    this.stage = new PIXI.Stage(0x000000, true);
    margin = 0;
    this.renderer = PIXI.autoDetectRenderer(window.innerWidth - margin, window.innerHeight - margin);
    PIXI.scaleModes.DEFAULT = PIXI.scaleModes.NEAREST;
    this.menu = new PIXI.DisplayObjectContainer();
    this.stage.addChild(this.menu);
    menuHeight = 100;
    this.base = new PIXI.DisplayObjectContainer();
    this.base.position.y = menuHeight;
    this.stage.addChild(this.base);
    offset = 0;
    g = new PIXI.Graphics();
    g.clear();
    g.lineStyle(0, 0xFFFFFF, 1);
    g.drawRect(0, 0, window.innerWidth, window.innerHeight);
    dumTex = g.generateTexture();
    this.stage.addChild(new PIXI.Sprite(dumTex));
    this.goalContainer = new PIXI.DisplayObjectContainer();
    this.goalContainer.count = 0;
    this.goalContainer.colorCount = [];
    this.helpContainer = new PIXI.DisplayObjectContainer();
    preloadImages();
  };


  /* Load assets into cache */

  this.preloadImages = function() {
    var assets, loader;
    assets = [this.siteprefix + "assets/img/galaxy-28.jpg", this.siteprefix + "assets/img/helpBackground.png", this.siteprefix + "assets/img/Icon_v2.png", this.siteprefix + "assets/img/hex-back.png", this.siteprefix + "assets/img/spark.png", this.siteprefix + "assets/img/crystal.png", this.siteprefix + "assets/img/connector-adjacent.png", this.siteprefix + "assets/img/connector-bridge.png", this.siteprefix + "assets/img/connector-far-neighbor.png", this.siteprefix + "assets/img/connector-none.png", this.siteprefix + "assets/img/connector-opposite.png"];
    loader = new PIXI.AssetLoader(assets);
    loader.onComplete = this.initFinish;
    loader.load();
  };


  /* Detect when the window is resized - jquery ftw! */

  window.onresize = function() {
    return window.resize();
  };


  /* Finish initing after assets are loaded */

  this.initFinish = function() {
    requestAnimFrame(window.animate);
    window.createHelpMenu();
    Board.loadBoard(window.BOARDNAME);
  };

}).call(this);
