// Generated by CoffeeScript 1.9.3

/* The various window-level values used. Kinda a constants file
requires: none
 */

(function() {
  this.typeIsArray = Array.isArray || function(value) {
    return {}.toString.call(value) === '[object Array]';
  };

  this.BOARDNAME = "board01";

  this.initted = false;

  this.gameOn = true;

  this.showWinContainer = true;

  this.difficulty = this.Game.MEDIUM;

  this.siteprefix = "";

}).call(this);
