// Generated by CoffeeScript 1.7.1

/* Makes and adds the win container. Called when the player beats this level */

(function() {
  this.makeWinGameContainer = function() {
    var close, contentStyle, headerStyle, nextLvl, title, topContent;
    this.winContainer = new PIXI.DisplayObjectContainer();
    this.winContainer.addChild(new PIXI.Sprite(new PIXI.Texture(PIXI.BaseTexture.fromImage(this.siteprefix + "assets/img/helpBackground.png"), new PIXI.Rectangle(0, 0, 500, 200))));
    this.winContainer.position.x = 450;
    this.winContainer.position.y = 250;
    headerStyle = {
      font: "bold 15px Futura",
      fill: "#6E6E6E"
    };
    contentStyle = {
      font: "15px Futura",
      fill: "#6E6E6E"
    };
    close = new PIXI.Text("X", {
      font: "bold 20px Sans-Serif",
      fill: "gray"
    });
    close.position.x = 480;
    close.position.y = 5;
    close.interactive = true;
    close.buttonMode = true;
    close.click = function() {
      window.stage.removeChild(window.winContainer);
      window.winContainer = null;
      window.gameOn = true;
      window.showWinContainer = false;
    };
    this.winContainer.addChild(close);
    title = new PIXI.Text("You Win!", headerStyle);
    title.position.x = 200;
    title.position.y = 10;
    this.winContainer.addChild(title);
    topContent = new PIXI.Text("You beat level " + this.level + " in " + this.BOARD.moves + " moves on " + this.Game.asString(this.difficulty) + " mode.", contentStyle);
    topContent.position.x = 20;
    topContent.position.y = 40;
    this.winContainer.addChild(topContent);
    if (this.level < 50) {
      nextLvl = new PIXI.Text((this.level + 1) + " >>", contentStyle);
      nextLvl.interactive = true;
    } else {
      nextLvl = new PIXI.Text("Thank you for playing!", contentStyle);
      nextLvl.interactive = false;
    }
    nextLvl.buttonMode = true;
    nextLvl.click = function() {
      var num;
      num = window.level + 1 < 10 ? "0" + (window.level + 1) : "" + (window.level + 1);
      window.BOARDNAME = "board" + num;
      window.menu.children[5].click();
    };
    nextLvl.position.x = 225;
    nextLvl.position.y = 175;
    this.winContainer.addChild(nextLvl);
    this.stage.addChild(this.winContainer);
    this.resize();
  };

}).call(this);
