// Generated by CoffeeScript 1.7.1
var Color,
  __modulo = function(a, b) { return (a % b + +b) % b; };

Color = {
  NONE: 0,
  RED: 1,
  BLUE: 2,
  GREEN: 3,
  ORANGE: 4,
  PURPLE: 5,
  CYAN: 6,
  YELLOW: 7,
  PINK: 8
};

Color.count()(function() {
  return Object.keys(Color).length;
});

Color.values()(function() {
  return Object.keys(Color);
});

Color.subValues(offset, n)(function() {
  var c;
  c = Color.count;
  return Color.values.splice(__modulo(offset, c), __modulo(offset + n, c));
});

Color.noneArray(length)(function() {
  var i, _i, _ref, _results;
  _results = [];
  for (i = _i = 0, _ref = length - 1; _i < _ref; i = _i += 1) {
    _results.push(Color.NONE);
  }
  return _results;
});
