// Generated by CoffeeScript 1.7.1

/* Creates a dummy board and adds to scope. Mainly for testing */

(function() {
  this.createDummyBoard = function() {
    this.BOARD = this.Board.makeBoard(4, 9, 3);
  };


  /* Draws the Board in BOARD on the stage. */

  this.drawBoard = function() {
    var h, _i, _len, _ref;
    _ref = this.BOARD.allHexes();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      h = _ref[_i];
      this.stage.addChild(spriteForHex(h));
    }
  };

  this.hexRad = 53;


  /* Creates a single sprite for a hex and adds it to stage */

  this.spriteForHex = function(hex) {
    var hexback, spr;
    if (typeof hex.sprite === "undefined" || hex.sprite === null) {
      hexback = PIXI.Texture.fromImage("assets/img/hex-back.png");
      spr = new PIXI.Sprite(hexback);
      spr.scale.x = 0.078;
      spr.scale.y = 0.078;
      spr.anchor.x = 0.5;
      spr.anchor.y = 0.5;
      spr.position.x = hex.loc.col * this.hexRad + this.hexRad / 2;
      spr.position.y = hex.loc.row * this.hexRad + this.hexRad / 2;
      hex.sprite = spr;
    }
    return hex.sprite;
  };

}).call(this);
