// Generated by CoffeeScript 1.7.1
var Game;

Game = (function() {

  /* Creates a game to wrap the given board */
  function Game(board) {
    this.setBoard(board);
  }


  /* Sets the board for this game - disposes of older board, if any */

  Game.prototype.setBoard = function(board) {
    if ((this.board !== null && this.board !== board)(this.board.dispose)) {
      return this.board = board;
    }
  };


  /* Returns the board for this game */

  Game.prototype.getBoard = function() {
    return this.board;
  };


  /* Called when a hex alters itself on the board - should repaint as necessary */

  Game.prototype.updateHex = function(h) {
    throw new RuntimeException("Can't Instantiate Type Game - updateHex must be overriden in subclasses");
  };


  /* Resets this game to its initial settings */

  Game.prototype.reset = function() {
    throw new RuntimeException("Can't Instantiate Type Game - reset must be overriden in subclasses");
  };


  /* Should return the difficulty of this game as an integer */

  Game.prototype.getDifficulty = function() {
    throw new RuntimeException("Can't Instantiate Type Game - getDifficulty must be overriden in subclasses");
  };

  return Game;

})();
