// Generated by CoffeeScript 1.7.1

/*A simple location class - nice int tuple.
 Using this over the Point class because constantly shifting from (x,y) to (col,row) is confusing
 */
var Loc;

Loc = (function() {
  function Loc(row, col) {
    this.row = row;
    this.col = col;
  }

  Loc.prototype.equals = function(o) {
    var l;
    if (!o instanceof Loc) {
      return false;
    } else {
      l = Loc(o);
      return this.row === l.row && this.col === l.col;
    }
  };

  Loc.prototype.toString = function() {
    return "(" + this.row + "," + this.col + ")";
  };

  Loc.NOWHERE = new Loc(-9999, -9999);

  return Loc;

})();
