// Generated by CoffeeScript 1.7.1
var Prism,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Prism = (function(_super) {
  __extends(Prism, _super);

  Prism.ROTATE_CLOCKWISE = true;


  /* Constructs a Prism and puts it into board b
     @param b - the board this prism belongs to
     @param l - the location of this prism in (row, col) in the board
     @param colors - the colors of this prism, in clockwise order starting with the top. Can be null, then set later.
     @throws IllegalArgumentException - if there is already hex at row,col, or row,col is OOB, or if colors is nonnull and length != SIDES.
   */

  function Prism(board, loc, colors) {
    Prism.__super__.constructor.call(this, board, loc);
    this.setColorCircle(colors);
  }


  /* Returns the colors of this prism, clockwise from the current top */

  Prism.prototype.colorArray = function() {
    return colorCircle.toArray();
  };


  /* Allows setting the ColorCircle, but only if it isn't set yet (is null).
     @throws IllegalArgumentException if the colorCircle is currently non-null
   */

  Prism.prototype.setColorCircle = function(colors) {
    if (colorCircle !== null) {
      throw new IllegalArgumentException("Can't set colorCirle of " + this.toString());
    }
    if (colors !== null && colors.length !== Hex.SIDES) {
      throw new IllegalArgumentException("Can't set color array of size " + colors.length);
    }
    this.colorCircle = ColorCircle.fromArray(colors);
  };

  Prism.prototype.rotate = function() {
    this.board.moves++;
    this.colorCircle = this.colorCircle.getPrevious();
    this.light();
  };

  Prism.prototype.rotateCounter = function() {
    this.board.moves++;
    this.colorCircle = this.colorCircle.getNext();
    this.light();
  };


  /* @Override
      Returns the colorCircle at the correct index for the color of a given side
   */

  Prism.prototype.colorOfSide = function(n) {
    if (n < 0 || n > Hex.SIDES - 1) {
      throw new IllegalArgumentException("Illegal Side Number " + n);
    }
    return this.colorCircle.toArray()[n];
  };


  /* @Override
     Tries to find light by looking at all neighbor hexes that this isn't providing light to
     Tries to stay the same color of light if multiple are avaliable. Otherwise chooses arbitrarily.
     Returns the color this is lit at the end of the procedure, false otherwise
   */

  Prism.prototype.light = function() {
    this.pruneLighters();
    this.stopProvidingLight();
    this.findLightProviders(Color.NONE);
    this.provideLight();
    this.update();
  };


  /* Default behavior for a Prism is to rotate. Rotates clockwise if ROTATE_CLOCKWISE, rotates counterclockwise otherwise. */

  Prism.prototype.click = function() {
    if (Prism.ROTATE_CLOCKWISE) {
      this.rotate();
    } else {
      this.rotateCounter();
    }
  };

  return Prism;

})(Hex);
